env:
  browser: true
  es2021: true
  jest: true
extends:
  - standard
  - plugin:boundaries/recommended
  - plugin:json/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - boundaries
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true,
  boundaries/ignore:
    - src/**/*.test.ts
  boundaries/elements:
    - type: core
      pattern: src/core/*
    - type: domain
      pattern: src/core/**/domain/*
    - type: usecase
      pattern: src/core/**/usecase/*
    - type: adapter
      pattern: src/core/**/adapter/*
    - type: api
      pattern: src/api/!(server/)*
    - type: cron
      pattern: src/cron/!(runner/)*
    - type: helper
      pattern: src/helper/*
rules:
  no-useless-constructor: off
  space-before-function-paren: off
  no-use-before-define: off
  boundaries/external:
    - 2
    - default: allow
      message: External dependencies are not allowed in this layer
      rules:
        - from:
          - domain
          - usecase
          - api
          - cron
          disallow: '*'
  boundaries/element-types:
    - 2
    - default: allow
      rules:
        - from: domain
          disallow:
            - helper
            - adapter
            - api
            - cron
          message: The domain layer can't have any external dependency.
        - from: usecase
          disallow:
            - helper
            - adapter
            - api
            - cron
          message: The usecase layer can't have any external dependency.
        - from: adapter
          disallow:
            - api
            - cron
          message: The adapter layer can't have any dependency from api or cron layers.
        - from: 
            - api
            - cron
          disallow: adapter
          message: The api/cron layer can't use an adapter directly. Use its service abstraction from de domain layer instead.
        - from: helper
          disallow:
            - core
            - api
            - cron
          message: A helper has to be self-contained and can't import any module from other layers
  